spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.41.74:3306/test
    username: root
    password: root1234
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zhc.demo.entity
server:
  port: 8081